-- 0066: Block disposable / temporary email signups (free, offline).
-- Client also checks shared/disposableEmail.ts; this is the hard server gate.
-- No paid APIs. Maintain domains in public.disposable_email_domains.

create table if not exists public.disposable_email_domains (
  domain text primary key
);

comment on table public.disposable_email_domains is
  'Known temporary/disposable email domains. Free blocklist; no external API.';

-- Seed / refresh common disposable domains (idempotent).
insert into public.disposable_email_domains (domain) values
  ('10minemail.com'),
  ('10minute-mail.com'),
  ('10minutemail.co.uk'),
  ('10minutemail.com'),
  ('10minutemail.de'),
  ('10minutemail.net'),
  ('10minutemail.nl'),
  ('10minutemail.pro'),
  ('10minutemail.us'),
  ('10minutemailbox.com'),
  ('10minutenemail.de'),
  ('1secmail.com'),
  ('1secmail.net'),
  ('1secmail.org'),
  ('1secmail.xyz'),
  ('20email.eu'),
  ('20minutemail.com'),
  ('20minutemail.it'),
  ('abyssmail.com'),
  ('anonymbox.com'),
  ('armyspy.com'),
  ('bheps.com'),
  ('binkmail.com'),
  ('bobmail.info'),
  ('burnermail.io'),
  ('cashette.com'),
  ('chammy.info'),
  ('cool.fr.nf'),
  ('courriel.fr.nf'),
  ('crazymailing.com'),
  ('cuvox.de'),
  ('dayrep.com'),
  ('dcctb.com'),
  ('devnullmail.com'),
  ('discard.email'),
  ('discardmail.com'),
  ('discardmail.de'),
  ('dispostable.com'),
  ('dpptd.com'),
  ('dropmail.me'),
  ('einrot.com'),
  ('einrot.de'),
  ('email-fake.com'),
  ('emailfake.com'),
  ('emailfake.ml'),
  ('emailnax.com'),
  ('emailondeck.com'),
  ('emailtemporanea.com'),
  ('emailtemporanea.net'),
  ('emailtemporar.ro'),
  ('emailtmp.com'),
  ('emz.net'),
  ('ephemail.net'),
  ('esiix.com'),
  ('explodemail.com'),
  ('express.net.ua'),
  ('eyepaste.com'),
  ('ezztt.com'),
  ('fake-box.com'),
  ('fakeinbox.com'),
  ('fakeinbox.info'),
  ('fakemail.fr'),
  ('fakemail.net'),
  ('fakemailgenerator.com'),
  ('filzmail.com'),
  ('fixail.com'),
  ('fleckens.hu'),
  ('frapmail.com'),
  ('generator.email'),
  ('getairmail.com'),
  ('getnada.com'),
  ('getonemail.com'),
  ('getonemail.net'),
  ('gishpuppy.com'),
  ('great-host.in'),
  ('grr.la'),
  ('gsrv.co.uk'),
  ('guerillamail.biz'),
  ('guerillamail.com'),
  ('guerillamail.de'),
  ('guerillamail.info'),
  ('guerillamail.net'),
  ('guerillamail.org'),
  ('guerrillamail.biz'),
  ('guerrillamail.com'),
  ('guerrillamail.de'),
  ('guerrillamail.info'),
  ('guerrillamail.net'),
  ('guerrillamail.org'),
  ('guerrillamailblock.com'),
  ('gustr.com'),
  ('haltospam.com'),
  ('hatespam.org'),
  ('hidemail.de'),
  ('hidzz.com'),
  ('icznn.com'),
  ('ieatspam.eu'),
  ('ieatspam.info'),
  ('ihateyoualot.info'),
  ('iheartspam.org'),
  ('imails.info'),
  ('inboxalias.com'),
  ('inboxbear.com'),
  ('inboxclean.com'),
  ('inboxclean.org'),
  ('inboxkitten.com'),
  ('incognitomail.com'),
  ('incognitomail.net'),
  ('incognitomail.org'),
  ('insorg-mail.info'),
  ('ipoo.org'),
  ('irish2me.com'),
  ('iwi.net'),
  ('jetable.com'),
  ('jetable.fr.nf'),
  ('jetable.net'),
  ('jetable.org'),
  ('jetable.pp.ua'),
  ('jnxjn.com'),
  ('jourrapide.com'),
  ('junk1e.com'),
  ('kasmail.com'),
  ('kaspop.com'),
  ('keepmymail.com'),
  ('killmail.com'),
  ('killmail.net'),
  ('kir.ch.tc'),
  ('klassmaster.com'),
  ('klassmaster.net'),
  ('klzlk.com'),
  ('kulturbetrieb.info'),
  ('kurzepost.de'),
  ('kzccv.com'),
  ('laafd.com'),
  ('lawlita.com'),
  ('lazyinbox.com'),
  ('letthemeatspam.com'),
  ('lhsdv.com'),
  ('lifebyfood.com'),
  ('link2mail.net'),
  ('linshiyouxiang.net'),
  ('litedrop.com'),
  ('lol.ovpn.to'),
  ('lookugly.com'),
  ('lopl.co.cc'),
  ('lortemail.dk'),
  ('lovemeleaveme.com'),
  ('lr78.com'),
  ('m4ilweb.info'),
  ('maboard.com'),
  ('mail-filter.com'),
  ('mail-temp.com'),
  ('mail-temporaire.fr'),
  ('mail.by'),
  ('mail.gw'),
  ('mail.mezimages.net'),
  ('mail.tm'),
  ('mail2rss.org'),
  ('mail333.com'),
  ('mail4trash.com'),
  ('mail7.io'),
  ('mailbidon.com'),
  ('mailblocks.com'),
  ('mailblog.biz'),
  ('mailbucket.org'),
  ('mailcat.biz'),
  ('mailcatch.com'),
  ('mailde.de'),
  ('mailde.info'),
  ('maildrop.cc'),
  ('maildrop.cf'),
  ('maildrop.ga'),
  ('maildrop.gq'),
  ('maildrop.ml'),
  ('maildu.de'),
  ('maileater.com'),
  ('mailed.ro'),
  ('maileimer.de'),
  ('mailexpire.com'),
  ('mailfa.tk'),
  ('mailforspam.com'),
  ('mailfreeonline.com'),
  ('mailguard.me'),
  ('mailhazard.com'),
  ('mailhazard.us'),
  ('mailhz.me'),
  ('mailimate.com'),
  ('mailin8r.com'),
  ('mailinater.com'),
  ('mailinator.biz'),
  ('mailinator.cl'),
  ('mailinator.co'),
  ('mailinator.com'),
  ('mailinator.info'),
  ('mailinator.net'),
  ('mailinator.org'),
  ('mailinator.us'),
  ('mailinator0.com'),
  ('mailinator1.com'),
  ('mailinator2.com'),
  ('mailinator99.com'),
  ('mailinatorapp.com'),
  ('mailincubator.com'),
  ('mailing.one'),
  ('mailismagic.com'),
  ('mailita.tk'),
  ('mailme.gq'),
  ('mailme.ir'),
  ('mailme.lv'),
  ('mailme24.com'),
  ('mailmetrash.com'),
  ('mailmoat.com'),
  ('mailms.com'),
  ('mailna.biz'),
  ('mailna.co'),
  ('mailna.in'),
  ('mailna.me'),
  ('mailnator.com'),
  ('mailnesia.com'),
  ('mailnull.com'),
  ('mailorg.org'),
  ('mailpick.biz'),
  ('mailpoof.com'),
  ('mailproxsy.com'),
  ('mailquack.com'),
  ('mailrock.biz'),
  ('mailsac.com'),
  ('mailscrap.com'),
  ('mailseal.de'),
  ('mailshell.com'),
  ('mailsiphon.com'),
  ('mailslapping.com'),
  ('mailslite.com'),
  ('mailsucker.net'),
  ('mailtemp.info'),
  ('mailtome.de'),
  ('mailtothis.com'),
  ('mailtrash.net'),
  ('mailtv.net'),
  ('mailtv.tv'),
  ('mailzi.ru'),
  ('mailzilla.com'),
  ('mailzilla.org'),
  ('makemetheking.com'),
  ('manifestgenerator.com'),
  ('manybrain.com'),
  ('mbx.cc'),
  ('mega.zik.dj'),
  ('meltmail.com'),
  ('messagebeamer.de'),
  ('mezimages.net'),
  ('mierdamail.com'),
  ('migmail.pl'),
  ('migumail.com'),
  ('mintemail.com'),
  ('minuteinbox.com'),
  ('minutemail.com'),
  ('mjukglass.nu'),
  ('moakt.com'),
  ('moakt.ws'),
  ('mobileninja.co.uk'),
  ('moburl.com'),
  ('mohmal.com'),
  ('mohmal.im'),
  ('mohmal.in'),
  ('mohmal.tech'),
  ('moncourrier.fr.nf'),
  ('monemail.fr.nf'),
  ('monmail.fr.nf'),
  ('monumentmail.com'),
  ('mswork.ru'),
  ('mt2009.com'),
  ('mt2014.com'),
  ('mt2015.com'),
  ('mvrht.com'),
  ('mvrht.net'),
  ('mypartyclip.de'),
  ('myphantomemail.com'),
  ('myspaceinc.com'),
  ('myspaceinc.net'),
  ('myspacepimpedup.com'),
  ('myspamless.com'),
  ('mytemp.email'),
  ('mytempemail.com'),
  ('mytempmail.com'),
  ('mytrashmail.com'),
  ('nada.email'),
  ('nada.ltd'),
  ('neomailbox.com'),
  ('nepwk.com'),
  ('nervmich.net'),
  ('nervtmich.net'),
  ('netmails.com'),
  ('netmails.net'),
  ('netzidiot.de'),
  ('neverbox.com'),
  ('nice-4u.com'),
  ('nincsmail.com'),
  ('nincsmail.hu'),
  ('nmail.cf'),
  ('nnh.com'),
  ('nobulk.com'),
  ('noclickemail.com'),
  ('nogmailspam.info'),
  ('nomail.pw'),
  ('nomail.xl.cx'),
  ('nomail2me.com'),
  ('nomorespamemails.com'),
  ('nonspam.eu'),
  ('nonspammer.de'),
  ('noref.in'),
  ('nospam.ze.tc'),
  ('nospam4.us'),
  ('nospamfor.us'),
  ('nospammail.net'),
  ('nospamthanks.info'),
  ('notmailinator.com'),
  ('notsharingmy.info'),
  ('nowhere.org'),
  ('nowmymail.com'),
  ('nurfuerspam.de'),
  ('nwldx.com'),
  ('objectmail.com'),
  ('obobbo.com'),
  ('odnorazovoe.ru'),
  ('one-time.email'),
  ('oneoffemail.com'),
  ('oneoffmail.com'),
  ('onewaymail.com'),
  ('onlatedotcom.info'),
  ('online.ms'),
  ('oopi.org'),
  ('oosln.com'),
  ('opayq.com'),
  ('ordinaryamerican.net'),
  ('otherinbox.com'),
  ('ourklips.com'),
  ('outlawspam.com'),
  ('ovpn.to'),
  ('owlpic.com'),
  ('pancakemail.com'),
  ('pjjkp.com'),
  ('plexolan.de'),
  ('plizcam.com'),
  ('pokemail.net'),
  ('politikerclub.de'),
  ('poofy.org'),
  ('pookmail.com'),
  ('privatdemail.net'),
  ('proxymail.eu'),
  ('prtnx.com'),
  ('putthisinyourspamdatabase.com'),
  ('pwrby.com'),
  ('qiott.com'),
  ('quickinbox.com'),
  ('quickmail.nl'),
  ('rcpt.at'),
  ('reallymymail.com'),
  ('realtyalerts.ca'),
  ('recode.me'),
  ('reconmail.com'),
  ('recursor.net'),
  ('recyclemail.dk'),
  ('regbypass.com'),
  ('regbypass.comsafe-mail.net'),
  ('rejectmail.com'),
  ('remail.cf'),
  ('remail.ga'),
  ('rhyta.com'),
  ('rklips.com'),
  ('rmqkr.net'),
  ('robot-mail.com'),
  ('royal.net'),
  ('rppkn.com'),
  ('rteet.com'),
  ('rtrtr.com'),
  ('s0ny.net'),
  ('safe-mail.net'),
  ('safersignup.de'),
  ('safetymail.info'),
  ('safetypost.de'),
  ('sandelf.de'),
  ('saynotospams.com'),
  ('schafmail.de'),
  ('schrott-email.de'),
  ('secretemail.de'),
  ('secure-mail.biz'),
  ('selfdestructingmail.com'),
  ('selfdestructingmail.org'),
  ('sendspamhere.com'),
  ('senseless-entertainment.com'),
  ('services391.com'),
  ('sharedmailbox.org'),
  ('sharklasers.com'),
  ('shieldedmail.com'),
  ('shiftmail.com'),
  ('shiftr.org'),
  ('shitmail.me'),
  ('shitmail.org'),
  ('shitware.nl'),
  ('shmeriously.com'),
  ('shortmail.net'),
  ('sibmail.com'),
  ('sinnlos-mail.de'),
  ('siteposter.net'),
  ('skeefmail.com'),
  ('slapsfromlastnight.com'),
  ('slaskpost.se'),
  ('slipry.net'),
  ('slopsbox.com'),
  ('slowslow.de'),
  ('slushmail.com'),
  ('smapfree24.com'),
  ('smapfree24.de'),
  ('smapfree24.eu'),
  ('smapfree24.info'),
  ('smapfree24.org'),
  ('smashmail.de'),
  ('smellfear.com'),
  ('snakemail.com'),
  ('sneakemail.com'),
  ('sneakmail.de'),
  ('snkmail.com'),
  ('sofimail.com'),
  ('sofort-mail.de'),
  ('sogetthis.com'),
  ('soisz.com'),
  ('solvemail.info'),
  ('soodonims.com'),
  ('spam.la'),
  ('spam.su'),
  ('spam4.me'),
  ('spamail.de'),
  ('spamarrest.com'),
  ('spamavert.com'),
  ('spambob.com'),
  ('spambob.net'),
  ('spambob.org'),
  ('spambog.com'),
  ('spambog.de'),
  ('spambog.net'),
  ('spambog.ru'),
  ('spambox.info'),
  ('spambox.irishspringrealty.com'),
  ('spambox.us'),
  ('spamcannon.com'),
  ('spamcannon.net'),
  ('spamcero.com'),
  ('spamcon.org'),
  ('spamcorptastic.com'),
  ('spamcowboy.com'),
  ('spamcowboy.net'),
  ('spamcowboy.org'),
  ('spamday.com'),
  ('spamdecoy.net'),
  ('spamex.com'),
  ('spamfighter.cf'),
  ('spamfighter.ga'),
  ('spamfighter.gq'),
  ('spamfighter.ml'),
  ('spamfighter.tk'),
  ('spamfree.eu'),
  ('spamfree24.com'),
  ('spamfree24.de'),
  ('spamfree24.eu'),
  ('spamfree24.info'),
  ('spamfree24.net'),
  ('spamfree24.org'),
  ('spamgoes.com'),
  ('spamgourmet.com'),
  ('spamgourmet.net'),
  ('spamgourmet.org'),
  ('spamherelots.com'),
  ('spamhereplease.com'),
  ('spamhole.com'),
  ('spamify.com'),
  ('spaminator.de'),
  ('spamkill.info'),
  ('spaml.com'),
  ('spaml.de'),
  ('spammotel.com'),
  ('spamobox.com'),
  ('spamoff.de'),
  ('spamsalad.in'),
  ('spamslicer.com'),
  ('spamspot.com'),
  ('spamstack.net'),
  ('spamthis.co.uk'),
  ('spamthisplease.com'),
  ('spamtrail.com'),
  ('spamtroll.net'),
  ('speed.1s.fr'),
  ('spoofmail.de'),
  ('stuffmail.de'),
  ('super-auswahl.de'),
  ('supergreatmail.com'),
  ('supermailer.jp'),
  ('superrito.com'),
  ('superstachel.de'),
  ('suremail.info'),
  ('svk.jp'),
  ('sweetxxx.de'),
  ('tafmail.com'),
  ('tagyourself.com'),
  ('talkinator.com'),
  ('tapchicuoihoi.com'),
  ('techemail.com'),
  ('techgroup.me'),
  ('teewars.org'),
  ('teleosaurs.xyz'),
  ('teleworm.com'),
  ('teleworm.us'),
  ('temp-mail.io'),
  ('temp-mail.org'),
  ('temp-mail.ru'),
  ('temp-mail.us'),
  ('temp.emeraldwebmail.com'),
  ('temp.headstrong.de'),
  ('tempail.com'),
  ('tempalias.com'),
  ('tempe-mail.com'),
  ('tempemail.biz'),
  ('tempemail.co.za'),
  ('tempemail.com'),
  ('tempemail.net'),
  ('tempinbox.co.uk'),
  ('tempinbox.com'),
  ('tempmail.cn'),
  ('tempmail.com'),
  ('tempmail.eu'),
  ('tempmail.it'),
  ('tempmail.net'),
  ('tempmail.plus'),
  ('tempmail.space'),
  ('tempmail.us.com'),
  ('tempmail2.com'),
  ('tempmailaddress.com'),
  ('tempmaildemo.com'),
  ('tempmailer.com'),
  ('tempmailer.de'),
  ('tempmailo.com'),
  ('tempomail.fr'),
  ('temporarily.de'),
  ('temporarioemail.com.br'),
  ('temporaryemail.net'),
  ('temporaryemail.us'),
  ('temporaryforwarding.com'),
  ('temporaryinbox.com'),
  ('temporarymailaddress.com'),
  ('tempr.email'),
  ('tempsky.com'),
  ('tempthe.net'),
  ('tempymail.com'),
  ('thanksnospam.info'),
  ('thankyou2010.com'),
  ('thc.st'),
  ('thelimestones.com'),
  ('thisisnotmyrealemail.com'),
  ('thismail.net'),
  ('throwam.com'),
  ('throwaway.email'),
  ('throwawayemailaddress.com'),
  ('throwawaymail.com'),
  ('tilien.com'),
  ('tittbit.in'),
  ('tizi.com'),
  ('tmail.ws'),
  ('tmailinator.com'),
  ('tmpbox.net'),
  ('tmpeml.com'),
  ('tmpmail.io'),
  ('tmpmail.net'),
  ('tmpmail.org'),
  ('tmpnator.live'),
  ('toiea.com'),
  ('toomail.biz'),
  ('topranklist.de'),
  ('tradermail.info'),
  ('trash-amil.com'),
  ('trash-mail.at'),
  ('trash-mail.com'),
  ('trash-mail.de'),
  ('trash-mail.ga'),
  ('trash-mail.gq'),
  ('trash-mail.ml'),
  ('trash-mail.tk'),
  ('trash2009.com'),
  ('trash2010.com'),
  ('trash2011.com'),
  ('trashdevil.com'),
  ('trashdevil.de'),
  ('trashemail.de'),
  ('trashmail.at'),
  ('trashmail.com'),
  ('trashmail.de'),
  ('trashmail.gq'),
  ('trashmail.me'),
  ('trashmail.net'),
  ('trashmail.org'),
  ('trashmail.ws'),
  ('trashmailer.com'),
  ('trashymail.com'),
  ('trashymail.net'),
  ('trbvm.com'),
  ('trbvn.com'),
  ('trbvo.com'),
  ('trialmail.de'),
  ('trillianpro.com'),
  ('tryalert.com'),
  ('turual.com'),
  ('twinmail.de'),
  ('twoweirdtricks.com'),
  ('txcct.com'),
  ('tyldd.com'),
  ('uggsrock.com'),
  ('umail.net'),
  ('upliftnow.com'),
  ('uplipht.com'),
  ('uroid.com'),
  ('us.af'),
  ('uuf.me'),
  ('venompen.com'),
  ('veryrealemail.com'),
  ('viditag.com'),
  ('viewcastmedia.com'),
  ('viewcastmedia.net'),
  ('viewcastmedia.org'),
  ('viralplays.com'),
  ('vjuum.com'),
  ('vkcode.ru'),
  ('vubby.com'),
  ('walala.org'),
  ('walkmail.net'),
  ('webemail.me'),
  ('webm4il.info'),
  ('webuser.in'),
  ('wh4f.org'),
  ('whyspam.me'),
  ('willhackforfood.biz'),
  ('willselfdestruct.com'),
  ('winemaven.info'),
  ('wronghead.com'),
  ('wuuvo.com'),
  ('wuzup.net'),
  ('wuzupmail.net'),
  ('wwjmp.com'),
  ('www.e4ward.com'),
  ('www.gishpuppy.com'),
  ('www.mailinator.com'),
  ('wwwnew.eu'),
  ('x.ip6.li'),
  ('xagloo.com'),
  ('xemaps.com'),
  ('xents.com'),
  ('xmaily.com'),
  ('xojxe.com'),
  ('xoxy.net'),
  ('yapped.net'),
  ('yep.it'),
  ('yogamaven.com'),
  ('yoggm.com'),
  ('yopmail.com'),
  ('yopmail.fr'),
  ('yopmail.gq'),
  ('yopmail.net'),
  ('youmailr.com'),
  ('ypmail.webarnak.fr.eu.org'),
  ('yuurok.com'),
  ('z1p.biz'),
  ('zehnminuten.de'),
  ('zehnminutenmail.de'),
  ('zetmail.com'),
  ('zippymail.info'),
  ('zoaxe.com'),
  ('zoemail.com'),
  ('zoemail.net'),
  ('zoemail.org'),
  ('zomg.info'),
  ('zwoho.com')
on conflict (domain) do nothing;

-- True when email uses a disposable domain (exact or subdomain of a listed host).
create or replace function public.is_disposable_email(p_email text)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_email text;
  v_domain text;
  v_parts text[];
  v_i int;
  v_candidate text;
begin
  v_email := lower(btrim(coalesce(p_email, '')));
  if v_email = '' or position('@' in v_email) < 2 then
    return false;
  end if;

  v_domain := split_part(v_email, '@', 2);
  v_domain := trim(both '.' from regexp_replace(v_domain, '\.+', '.', 'g'));
  if v_domain = '' or position('.' in v_domain) = 0 then
    return false;
  end if;

  -- Exact + parent-suffix match (a.b.mailinator.com → mailinator.com)
  v_parts := string_to_array(v_domain, '.');
  for v_i in 1 .. (array_length(v_parts, 1) - 1) loop
    v_candidate := array_to_string(v_parts[v_i : array_length(v_parts, 1)], '.');
    if exists (
      select 1 from public.disposable_email_domains d where d.domain = v_candidate
    ) then
      return true;
    end if;
  end loop;

  -- Brand-pattern catch-all for common temp-mail families (still free / offline).
  if v_domain ~* '(^|\.)(temp-?mail|tempmail|tmpmail|tmpeml|tmpbox|mailinator|yopmail|guerrill?a-?mail|sharklasers|maildrop|getnada|mailnesia|discard(mail)?|dispostable|fakeinbox|fakemail|emailfake|tempail|tempinbox|mintemail|mytemp\.?email|tempmailo|crazymailing|mailpoof|inboxkitten|burnermail|emailondeck|mailnull|spamgourmet|mailforspam|minuteinbox|mail-temp|tempr\.email|tempmailer|mailtemp|moakt|mohmal|1secmail|dropmail\.me|mail\.tm|mail\.gw|jetable|spamfree24|willselfdestruct|selfdestructingmail|mailsac|(10|15|20)minut?e?s?-?mail|throw-?away|trash-?mail|trashy?mail)([.-]|$)'
     or v_domain ~* '(^|\.)(spam4\.me|gustr\.com|dayrep\.com|einrot\.(com|de)|teleworm\.(com|us)|armyspy\.com|cuvox\.de|rhyta\.com|jourrapide\.com|superrito\.com)$'
  then
    return true;
  end if;

  return false;
end;
$$;

revoke all on function public.is_disposable_email(text) from public;
grant execute on function public.is_disposable_email(text) to authenticated, anon, service_role;

-- Reject disposable emails on auth.users insert/update (cannot be bypassed from clients).
create or replace function public.reject_disposable_auth_email()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_disposable_email(new.email) then
    raise exception 'disposable_email_not_allowed'
      using errcode = 'P0001',
            hint = 'Use a permanent email address.';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_reject_disposable_auth_email_ins on auth.users;
create trigger trg_reject_disposable_auth_email_ins
  before insert on auth.users
  for each row
  execute function public.reject_disposable_auth_email();

drop trigger if exists trg_reject_disposable_auth_email_upd on auth.users;
create trigger trg_reject_disposable_auth_email_upd
  before update of email on auth.users
  for each row
  when (new.email is distinct from old.email)
  execute function public.reject_disposable_auth_email();

-- Allow owner/admin to maintain the list without code deploys (optional ops).
alter table public.disposable_email_domains enable row level security;

drop policy if exists disposable_domains_read on public.disposable_email_domains;
-- No public read needed; function is security definer. Keep table locked down.
-- service_role / postgres can still write.

grant select, insert, delete on public.disposable_email_domains to service_role;
